name: Code Style

on:
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.0.0
    - run: npm install
    - name: Prettier
      run: prettier '*.js'
    - name: ESLint
      run: eslint '*.js'
