name: Git Checks

on:
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.0.0
    - name: npm run lint
      run: npm run lint
